import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { MissionMode } from "@/components/mission-mode";
import { getStore } from "@/lib/db";
import { getCurrentUser } from "@/lib/session";

export const dynamic = "force-dynamic";
export const metadata = { title: "Mission mode" };

/**
 * Mission mode lives outside the site chrome on purpose: no header, no footer,
 * no navigation to fall back into. Only the mission.
 */
export default async function MissionPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const user = await getCurrentUser();
  if (!user) redirect("/onboarding");

  const store = await getStore();
  const mission = await store.getMission(id);
  if (!mission || mission.userId !== user.id) notFound();

  return (
    <>
      <MissionMode mission={mission} />
      <p className="px-5 pb-6 text-center text-[11px] text-muted-foreground">
        Mission generated by {mission.generatedBy === "local" ? "the local model" : mission.generatedBy}{" "}
        ({mission.model}).{" "}
        <Link href="/privacy" className="underline-offset-4 hover:underline">
          Privacy
        </Link>
      </p>
    </>
  );
}
